name: credit-risk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.5.3
  - numpy=1.24.4
  - sqlalchemy=1.4.49
  - psycopg2  # PostgreSQL connector for SQLAlchemy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - python-dotenv
  - prettytable=2.5.0
  - streamlit
  
